export const directory = 
[
    {
        id: 0,
        name: "Succulents",
        src: "/img/succulents.jpg", 
        description: "Succulents have the ability to thrive on limited water sources, such as mist and dew, which makes them equipped to survive in an ecosystem that contains scarce water sources.",
        price: "$9.99",
        path: "/succulents",
    },
    {
        id: 1,
        name: "Perennials",
        src: "/img/pern.jpeg", 
        description: "Plants that persist for many growing seasons. You only plant them once and they come back every year. The top portion of the plant dies back each winter and regrows the following spring.",
        price: "$9.99",
        path: "/perennials",
    },
    {
        id: 2,
        name: "Ferns",
        src: "/img/ferns.jpg", 
        description: "Flowerless plants which has feathery or leafy fronds and reproduces by spores released from the undersides of the fronds. Ferns have a vascular system for the transport of water and nutrients.",
        price: "$9.99",
        path: "/ferns",
    },
    {
        id: 3,
        name: "Exotics",
        src: "/img/exotic.jpg", 
        description: "Plants that has been introduced to an area from outside its native range. Several different variants of species are included from venus fly traps to bamboo.",
        price: "$9.99",
        path: "/exotics",
    },
    {
        id: 4,
        name: "Cactus",
        src: "/img/cacti.jpg", 
        description: "Cactus will steal your heart with their charming, prickly forms and showy flowers. They require some caution when handling, but are super low maintenance.",
        price: "$9.99",
        path: "/cactus",
    },
    {
        id: 5,
        name: "Foilage",
        src: "/img/foilage.jpg", 
        description: "These are indoor plants grown primarily for their great looking and interesting leaves, rather than flowers. Keep the soil moist, but not continually saturated with water.",
        price: "$9.99",
        path: "/foilage",
    },
]